import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import devAvatar from '../public/images/burakbo.jpg'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Oguzhan Burak Bozkurt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
          <link rel="preload"
                href="/public/fonts/MSBee-Thin.woff2"
                as="font"
                crossOrigin=""/>
      </Head>

      <main>
        <h2 className={styles.title}>Oguzhan Burak Bozkurt</h2>
        <Image className={styles.avatar} src={devAvatar}/>
        <p className={styles.plang}>
          Kotlin / TypeScript / Java
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
